version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: flood_rescue_mysql_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: devpassword
      MYSQL_DATABASE: flood_rescue_dev
    ports:
      - "3307:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql

volumes:
  mysql_dev_data:
